### ISSUE TITLE
Add multiple jumps from a node

### ISSUE THREAD

**Issue by macfire** [raydac/netbeans-mmd-plugin#27]
Would it be possible to add multiple jumps from a node?

```
Node_0.0
|
|-Node_1.0
|    |- Node_1.1
|    |- Node_1.2 (Jump to Node_2.0 AND jump to Node_3.0)
|                        |                   |
|-Node_2.0 <-------------|                   |
|                                            |
|-Node_3.0  <--------------------------------|
```

**Comment by raydac** [comment]
it looks like that you are trying to make just a graph diagram instead of a mind map, IMHO the mind map way to have multiple jumps is to add several children to a topic and each child will have a described jump
![example](https://raw.githubusercontent.com/raydac/netbeans-mmd-plugin/master/assets/misc/multijumps.png)

**Comment by macfire** [comment]
@raydac 
Thanks for the explanation. It does make sense to describe the purpose of jump.
