### ISSUE TITLE
After right-clicking to add a picture, you can't zoom in after visiting this picture

### ISSUE THREAD

**Issue by lidadaer** [raydac/netbeans-mmd-plugin#58]
After right-clicking to add a picture, you can't zoom in after visiting this picture

**Comment by raydac** [comment]
could you explain in some details step-by-step, how to reproduce?

**Comment by lidadaer** [comment]
![image](https://user-images.githubusercontent.com/18696347/70787744-4ff0c580-1dca-11ea-89e9-a24c4bd53b86.png)
![image](https://user-images.githubusercontent.com/18696347/70787772-5f700e80-1dca-11ea-9e06-3a674dce014d.png)

**Comment by raydac** [comment]
during adding, the picture is resized to be displayable in the topic, there is not any functionality to open it in full-size after resize
if keep original images in mind map file then it would be too big.. so that such pictures mainly play role of some thumbnails, you could just add file link to the original picture file in the mind map element and double click on it would open original image file

**Comment by lidadaer** [comment]
Thank you for your help. It's also a very good plug-in.

**Comment by raydac** [comment]
in 1.4.7-SNAPSHOT version, the image plugin has been improved to provide way keep path to original image file and open it through double click
